### ISSUE TITLE
Pre-build MacOS isn't signed and can't be opened

### ISSUE THREAD

**Issue by RS102839** [xolentum/gui-wallet#18]
When trying to run the GUI wallet on MacOS, the OS refuses to allow it as unsigned:

**_

> “Xolentum GUI Wallet 2” can’t be opened because it is from an unidentified developer.
> 
> Your security preferences allow installation of only apps from the App Store and identified developers.
> 
> Firefox downloaded this file on April 20, 2021 from www.xolentum.org.

_**

**Comment by sn1f3rt** [comment]
This is because it isn't notarized (that is, signed by any Mac Developer certificate), the binary is technically safe as it has been signed by GPG, verification steps are on the Releases page. 

Please check out the _How to open an app that hasn’t been notarized or is from an unidentified developer_ section, of this support article https://support.apple.com/en-in/HT202491, on how to install the application.

**Comment by RS102839** [comment]
Then my suggestion is to notarize it and properly sign it.

I can build from source, but I'm not installing unsigned applications from third parties, nor should any sensible user (IMHO)

**Comment by sn1f3rt** [comment]
It's not that I do not want to, but well I'm unable to. The notarization process requires a valid Mac Developer Certificate, and to obtain that I have to sign up for the Mac Developers Program, which has a cost associated with it. 

As I said earlier, GPG signed binaries with SHA-256 hash check should be good to use as they are the original copy, the same GUI wallet gets built for all platforms so there cannot be any issues associated with the Mac-specific build, it's just that Apple requires that extra step in order to authorize an application. 

However, I do respect your thoughts, in the present situation, you'll have to use the CLI wallet or the web wallet in case you choose not to install the GUI wallet in it's current state.

**Comment by RS102839** [comment]
Yes, I understand.   Thanks for the reply, BTW.

Might I suggest you provide a link to online wallets that support XOLfor people trying out Xolentum, but unwilling to install an unsigned application?

**Comment by sn1f3rt** [comment]
Sure, you can head to the web wallet. https://xolon.live/
